name: Status Check
on: [pull_request]
jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
         jenkins-url: 'http://52.14.62.107:8080/job/multi-branch/'
         jenkins-user: 'admin'
         jenkins-token: ${{ secrets.MYTOKEN }}
         job-name: 'multi-branch'
    - name: Build and test
      run: |
        curl -X POST -u "11dd4f8085055bba9af35e07a7f19501eb" http://52.14.62.107:8080/job/multi-branch/
